# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlxMo9Y-Z2BqEI2XF3KINTYxRn0KtUwI
"""

!pip install --upgrade pip


!pip install tensorflow

!pip install keras --upgrade

import pandas as pd
import numpy as np
import tensorflow as tf

df = pd.read_csv("/content/Folds5x2_pp.csv")

df.head(5)

X = df.drop("PE" , axis = 1)
Y = df["PE"]

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state=42)

ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 6,activation = "relu", input_dim=4)) #units kaç tane sinir olacağı ,  activation fonk. ismi , input_dim X'teki column sayısı

ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

ann.add(tf.keras.layers.Dense(units = 1))

ann.compile(optimizer = "adam",loss= "mean_squared_error")

ann.fit(X_train,Y_train,epochs = 100)

y_pred = ann.predict(X_test)

for i in y_pred:
  print(i , end ="    ")

for i in y:
  print(i , end ="   ")

